# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5a038536b6e1929436e6f902f78c297032b86d15c6e2a297e3cac3d8b706ba74c9f456aeb2b74cdc6c0d3d5f22c206601f28fcc9a0d15a6e7a74b25cee718201

test:
  secret_key_base: 1fdc3aa9d305f4fd48a62f9de95d930b6a1bf35cafeb3a39fa69a00ff2cc91949479369223881ade08f831f780006de7d3b6a3dc14060e4d1683715cd27f8342

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
